#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Ask mysql root password?
db_input high octopussy/mysql_root_password || true
db_go

# Check their answer.
#db_get octopussy/mysql_root_password
