#!/bin/sh -e

OCTO="octopussy"
INVOKERCD="/usr/sbin/invoke-rc.d"
USERDEL="/usr/sbin/userdel"

if [ -x "/etc/init.d/$OCTO" ]; then
 	$INVOKERCD $OCTO stop || exit 0
fi

#
# Remove Octopussy User
#
$USERDEL $OCTO || true
