#!/usr/bin/perl -w
=head1 NAME

octo_commander - Octopussy Commander program

=head1 SYNOPSIS

octo_commander 

=head1 DESCRIPTION

octo_commander is the program used by the Octopussy Project to launch command from WebInterface

=cut
use strict;
use warnings;
use Readonly;

use Octopussy;

Readonly my $PROG_NAME => "octo_commander";

if (!Octopussy::Valid_User())
{
  print "You need to be Octopussy user to use $PROG_NAME !\n";
  exit;
}

my $cache = Octopussy::Cache::Init($PROG_NAME);
while (1)
{
	my $commands = $cache->get("commands");
	$cache->remove("commands"); # TODO If cache set between get & remove ?
	foreach my $c (@{$commands})
		{ system($c)	if ($c =~ /^\/usr\/sbin\/octo.+/); }
	sleep(1);
}
