#!/usr/bin/perl -w
=head1 NAME

octo_world_stats - Octopussy World Statistics program

=head1 DESCRIPTION

octo_world_stats sends statistics data to 8pussy.org to see Octopussy usage in the world

=cut
use strict;
use Date::Manip;
use URI::Escape;
use Octopussy;

use constant APPLI => "Octopussy";
use constant PROG_NAME => "octo_world_stats";
my $update_url = Octopussy::Parameter("url_world_stats_update");

my $conf = Octopussy::World_Stats::Configuration();
if ($conf->{status} eq "enabled")
{
  my ($id, $country) = ($conf->{id}, $conf->{country});

  my $dir_pid = Octopussy::Directory("running");
  my $cache = Octopussy::Cache::Init("octo_dispatcher");
  my $version = Octopussy::Version();
  my $cpu = Octopussy::Stats::CPU_Info();
  $cpu =~ s/\s+/ /g;
  $cpu = uri_escape($cpu);
  my $mem = Octopussy::Stats::Mem_Total();
  my @devices = Octopussy::Device::List();
  my @services = Octopussy::Device::Services(@devices);
  my $nb_devices = scalar(@devices);
  my $nb_services = scalar(@services);
  my @keys = $cache->get_keys();
	my ($y, $m, $d, $h) = AAT::Datetime::Now();
  foreach my $k (sort @keys)
  {
    if (($k =~ /^dispatcher_stats_hourly_(\d{10})$/) && ($1 !~ /^$y$m$d$h$/))
    {
			my $hour = $1;
      my $url = "$update_url?id=$id&country=$country&version=$version"
				. "&cpu=$cpu&memory=$mem&hour=$hour&nb_devices=$nb_devices"
				. "&nb_services=$nb_services&nb_logs=" . ($cache->get($k) || "0");
			AAT::Download(APPLI, $url, "/dev/null");
    }
  }
  AAT::Syslog("octo_world_stats", "WORLD_STATS_SENT");
}
else
{
  print "World Statistics are disabled !\n";
}

=head1 AUTHOR

Sebastien Thebert <octo.devel@gmail.com>

=head1 SEE ALSO

octo_dispatcher, octo_extractor, octo_parser, octo_uparser, octo_scheduler

=cut
