<AAT:Form action="$url">
<AAT:Box align="C">
<AAT:BoxRow>
	<AAT:BoxCol cspan="2">
 	<AAT:Inc file="octo_selector_search_template" selected="" /></AAT:BoxCol>
</AAT:BoxRow>
<AAT:BoxRow>
	<AAT:BoxCol>
  <AAT:Entry name="template" value="enter your template name" size="40" />
  </AAT:BoxCol>
  <AAT:BoxCol><AAT:Form_Submit value="_SAVE_AS_SEARCH_TEMPLATE" /></AAT:BoxCol>
</AAT:BoxRow>
</AAT:Box>
</AAT:Form>
